### ISSUE TITLE
Is 1.20.* planned?

### ISSUE THREAD

**Issue by iambeingtracked** [Splzh/ClearHitboxes#3]
I know it's kind of dumb to ask such questions, but your mod is so good that I can't play well without it

**Comment by Splzh** [comment]
Apologies for the 2 week wait for a response. It is currently planned,
however I was a bit busy the last few months. I will continue development
over the next few days. Thank you for using Clear Hitboxes.

**Comment by iambeingtracked** [comment]
Glad you replied, thanks for developing!

**Comment by Splzh** [comment]
I have just submitted the 1.20 Beta, so I will mark this as closed, thanks for the issue and your time.

**Comment by iambeingtracked** [comment]
Thanks, why is there no new commits there on Github though?

**Comment by iambeingtracked** [comment]
Hey, will there be source code released?
